components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-22.0.2
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 373eb7767186f0d185f249cfee7014b756130d54
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.2.4-5
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    revision: fe6575134c90abddb27cde304c8eeb3d2520efed
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 0485b5dc951ddd09298c68dd7e520f51ba6db569
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.7.9
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 3c5dc985d21d0b863fc6da1fb39a5211d132e7cc-1835
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1854
version: '1'
