components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-22.1.2
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 62ab67c46dad5713d50702d3a5893e2398a99343
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.2.4-5
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    revision: 3d1df2ecc8b05ffd9f174131cbeff2ab608f9542
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 1898-154
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: c9a9f1c0d46f51b116cd9cb562205b20d33539ed
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.7.15
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 5e00a0c1148dfea10b3a934521597896c8e7d32d-1885
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1898
version: '1'
