components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-21.2.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 5d5672d6cc0c415dae76648390026f777004bd99
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.2.3
    repository: https://github.com/intel/igsc.git
  infra:
    branch: infra
    dest_dir: infra
    revision: 6c885c1e2c46a610c46c55b463dd50ff9c48cb49
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: f3bb2f527767ec4e032fab6b8bf460dbc7531f4a
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.4.1
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: ea9d6f9b757307608e21f780bbd59e1345a3fdba-1746
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1753
version: '1'
