components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.3.2
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 776459c9e42d2f0270820e1f0d589f391475d933
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 77311eaed144e0c3b69240d4de87eeaae48a3080
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: cf1ff6a0ac758486fa517bc672c8823f866cf47f
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.0.22
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: a7f41ae89e3c0ed35c308e5b8c8bb1c8db1a78bb-1543
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1558
version: '1'
