components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-21.3.4
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 43e0b0f78fa7631b00a1aa7a421ce5c004b253d7
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.2.4-5
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    revision: f64dba1a2c34b1618b302a56feb3c7d41e3775b7
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 0485b5dc951ddd09298c68dd7e520f51ba6db569
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.6.2
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: ea9d6f9b757307608e21f780bbd59e1345a3fdba-1746
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1827
version: '1'
