components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: 11f846a14596f2ac5152055052d52baaa3721320
    type: git
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-22.1.8
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: a3d06ca6798d1c70bb0bf274695ac74ce0532ae4
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.8.4-1
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    fetch_tags: true
    revision: v4160
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 1957-368
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 0327332b4f9a342d2c49b65a3676c676b5fb2d4c
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.8.5
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 88d945722b59435cc108a6ec4d785a811418f592-1957
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1957
version: '1'
