components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: e854a7b82ed4991a56920853c2b5d5763df4ca3b
    type: git
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-22.3.0
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 0f1e74533f464ade7f88f5d58c579cdc5621a755
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.8.4-1
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    fetch_tags: true
    revision: v4375
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 1982-409
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 0327332b4f9a342d2c49b65a3676c676b5fb2d4c
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.8.8
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  metrics-discovery:
    dest_dir: metrics/discovery
    type: git
    branch: metrics-discovery
    revision: metrics-discovery-1.12.155
    repository: https://github.com/intel/metrics-discovery.git
  metrics-library:
    dest_dir: metrics/library
    type: git
    branch: metrics-library
    revision: metrics-library-1.0.114
    repository: https://github.com/intel/metrics-library.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 6345c07d848f2c632c92523229d284e5a35635c6-1982
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1982
version: '1'
