components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.2.5
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: d9b1967f86881a96bc2344118d5cc425d09c4810
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: dbbe5697ba209c04068460765099e66c86373c9c
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 321eaa2abedf8d6165cbe9214d05da8de83ffc88
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 18a7db778c3ec50265d3d88810f93892e18fbb2a
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.0
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 289b773d83bd936ae78c0475ae967393dd95f44b-1467
converter: M-1467
version: '1'
